version: "3.7"
services:

  flask_app:
    image: 'careerdevelopmentchatbot:release_v4'
    ports:
      - "7006:7006"
    depends_on:
      - rabbit

  rabbit:
    hostname: rabbit
    image: "rabbitmq:3-management"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "15672:15672"
      - "5672:5672"

  simple_worker:
    image: 'careerdevelopmentchatbot_augmentationmodel_worker:release_v4'
#    user: nobody
    depends_on:
      - rabbit
      - flask_app